# Generated by Django 6.0.5 on 2026-05-27 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('emission', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FLAGGED', 'FLAGGED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('LOCKED', 'LOCKED')], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('ingestion_status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.emissionrecord')),
            ],
        ),
    ]
